name = "NeighborListTools"
uuid = "252c77ef-e869-45fc-9102-44933f8f3486"
authors = ["Teemu Järvinen and Timon S. Gutleb"]
version = "0.1.0-DEV"

[deps]
AtomsBase = "a963bdd2-2df7-4f54-a1ee-49d51e6be12a"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
AtomsBase = "0.3"
StaticArrays = "1"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
